[common]
; false 才能用 ?url= 传你的机场订阅；true 会禁止 url 参数
api_mode=false
exclude_remarks=(到期|剩余时间|官网|产品|QQ群|网址)
prepend_insert_url=true
enable_insert=false

[managed_config]
write_managed_config=false

[server]
listen=0.0.0.0
port=8080
